### ISSUE TITLE
setOptimizationLevel to 1 

### ISSUE THREAD

**Issue by HugoGresse** [F43nd1r/rhino-android-example#2]
I'm having issue if I follow the [example](https://github.com/F43nd1r/rhino-android-example/blob/master/src/main/java/com/faendir/rhino_android/MainActivity.java#L33) and use setOptimizationLevel(1). I need to use optimization -1 to work correctly. Also, can you point out what the advantages of the wrapper. I've quick tested the rhino jar and have a little better perf (like 15% faster) 

```
com.myapplication W/System.err: UNEXPECTED TOP-LEVEL EXCEPTION:
com.myapplication W/System.err: java.util.zip.ZipException: Duplicate entry name: org/mozilla/javascript/gen/ScriptAPI_1.class
com.myapplication W/System.err:     at java.util.zip.ZipFile.readCentralDir(ZipFile.java:444)
com.myapplication W/System.err:     at java.util.zip.ZipFile.<init>(ZipFile.java:163)
com.myapplication W/System.err:     at java.util.zip.ZipFile.<init>(ZipFile.java:119)
com.myapplication W/System.err:     at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
com.myapplication W/System.err:     at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
com.myapplication W/System.err:     at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
com.myapplication W/System.err:     at com.android.dx.command.dexer.Main.processOne(Main.java:672)
com.myapplication W/System.err:     at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
com.myapplication W/System.err:     at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
com.myapplication W/System.err:     at com.android.dx.command.dexer.Main.run(Main.java:277)
com.myapplication W/System.err:     at com.faendir.rhino_android.AndroidClassLoader.dexJar(AndroidClassLoader.java:103)
com.myapplication W/System.err:     at com.faendir.rhino_android.AndroidClassLoader.defineClass(AndroidClassLoader.java:64)
com.myapplication W/System.err:     at org.mozilla.javascript.optimizer.Codegen.defineClass(Codegen.java:130)
com.myapplication W/System.err:     at org.mozilla.javascript.optimizer.Codegen.createScriptObject(Codegen.java:85)
com.myapplication W/System.err:     at org.mozilla.javascript.Context.compileImpl(Context.java:2534)
com.myapplication W/System.err:     at org.mozilla.javascript.Context.compileString(Context.java:1476)
com.myapplication W/System.err:     at org.mozilla.javascript.Context.compileString(Context.java:1465)
com.myapplication W/System.err:     at org.mozilla.javascript.Context.evaluateString(Context.java:1216)
com.myapplication W/System.err:     at tv.teads.myapplication.RhinoAarTest.<init>(RhinoAarTest.java:32)
com.myapplication W/System.err:     at tv.teads.myapplication.MainActivity$5.onClick(MainActivity.java:89)
com.myapplication W/System.err:     at android.view.View.performClick(View.java:4785)
com.myapplication W/System.err:     at android.view.View$PerformClick.run(View.java:19884)
com.myapplication W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
com.myapplication W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
com.myapplication W/System.err:     at android.os.Looper.loop(Looper.java:135)
com.myapplication W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5343)
com.myapplication W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
com.myapplication W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
com.myapplication W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
com.myapplication W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
com.myapplication W/System.err: 1 error; aborting
com.myapplication D/AndroidRuntime: Shutting down VM
com.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                            Process: tv.teads.myapplication, PID: 10557
                                            com.faendir.rhino_android.AndroidClassLoader$FatalLoadingException: Failed to define class
                                                at com.faendir.rhino_android.AndroidClassLoader.defineClass(AndroidClassLoader.java:66)
                                                at org.mozilla.javascript.optimizer.Codegen.defineClass(Codegen.java:130)
                                                at org.mozilla.javascript.optimizer.Codegen.createScriptObject(Codegen.java:85)
                                                at org.mozilla.javascript.Context.compileImpl(Context.java:2534)
                                                at org.mozilla.javascript.Context.compileString(Context.java:1476)
                                                at org.mozilla.javascript.Context.compileString(Context.java:1465)
                                                at org.mozilla.javascript.Context.evaluateString(Context.java:1216)
                                                at tv.teads.myapplication.RhinoAarTest.<init>(RhinoAarTest.java:32)
                                                at tv.teads.myapplication.MainActivity$5.onClick(MainActivity.java:89)
                                                at android.view.View.performClick(View.java:4785)
                                                at android.view.View$PerformClick.run(View.java:19884)
                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                at android.os.Looper.loop(Looper.java:135)
                                                at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                at java.lang.reflect.Method.invoke(Native Method)
                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                             Caused by: java.io.IOException: Unable to open '/data/data/tv.teads.myapplication/cache/classes/dex-739948924.jar' : No such file or directory
                                                at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                at dalvik.system.DexFile.openDexFile(DexFile.java:295)
                                                at dalvik.system.DexFile.<init>(DexFile.java:111)
                                                at dalvik.system.DexFile.loadDex(DexFile.java:151)
                                                at com.faendir.rhino_android.AndroidClassLoader.dexJar(AndroidClassLoader.java:104)
                                                at com.faendir.rhino_android.AndroidClassLoader.defineClass(AndroidClassLoader.java:64)
                                                at org.mozilla.javascript.optimizer.Codegen.defineClass(Codegen.java:130) 
                                                at org.mozilla.javascript.optimizer.Codegen.createScriptObject(Codegen.java:85) 
                                                at org.mozilla.javascript.Context.compileImpl(Context.java:2534) 
                                                at org.mozilla.javascript.Context.compileString(Context.java:1476) 
                                                at org.mozilla.javascript.Context.compileString(Context.java:1465) 
                                                at org.mozilla.javascript.Context.evaluateString(Context.java:1216) 
                                                at tv.teads.myapplication.RhinoAarTest.<init>(RhinoAarTest.java:32) 
                                                at tv.teads.myapplication.MainActivity$5.onClick(MainActivity.java:89) 
                                                at android.view.View.performClick(View.java:4785) 
                                                at android.view.View$PerformClick.run(View.java:19884) 
                                                at android.os.Handler.handleCallback(Handler.java:739) 
                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                at android.os.Looper.loop(Looper.java:135) 
                                                at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
```

**Comment by F43nd1r** [comment]
This wrapper should enable the use of optimization levels. In addition, it is the only way to use JavaAdapter on Android.
Performance varies based on Complexity. For small scripts the interpreted mode will be faster (although there should be no difference between this wrapper and the original). For complex scripts compilation should be faster. Compilation only works with the wrapper (but it might be broken, according to your stacktrace).

**Comment by F43nd1r** [comment]
I just tested the sample and I could not reproduce your issue. What device are you using? What code are you running?

**Comment by AlexTrotsenko** [comment]
@F43nd1r I have the same issue when I re-compile the same function 2nd time on app's re-start in my test project: 
https://github.com/AlexTrotsenko/RhinoCompiledTest

Also my perf result is much better if I re-use already re-compiled function to run the code 
_(new scope and context could be provided at the invocation time)_

**Comment by F43nd1r** [comment]
@AlexTrotsenko I pulled your sample project and ran it a few times. I see no problems before or after restarting the app.
